### ISSUE TITLE
E il PUN del giorno dopo?

### ISSUE THREAD

**Issue by CreasolTech** [virtualdj/pun-fasce#1]
Ciao, 
trovo mooolto interessante lo script per avere il PUN medio per fascia. 
C'e' anche il modo di conoscere il PUN del giorno dopo? Mi piacerebbe utilizzare tali dati per programmare la pompa di calore e la ricarica dell'auto negli orari in cui il PUN è più basso (solo per una ragione ecologica), cosiccome ridurre i consumi o esportare energia quando il PUN è alto, in modo da aiutare la rete.
Intanto complimenti!

**Comment by virtualdj** [comment]
Ciao, tecnicamente questo script fa la media dei prezzi delle fasce per calcolare il valore mensile finale che è poi lo stesso delle tabelle pubblicate dai vari fornitori (es. A2A).
Quindi il prezzo del giorno dopo, seppur si possa estrarre con qualche modifica, dove dovrei visualizzarlo? Servirebbe un parametro ad-hoc.

Poi come lo usi il dato per attivare la pompa di calore? Sarebbe più comodo usare l'altro progetto [pun_sensor](https://github.com/virtualdj/pun_sensor) da Home Assistant.

Ma, anche lì, non credo abbia senso modificarlo per aggiungere i valori del giorno dopo perché comunque, anche se fossero alti, andrebbero in media con quelli dei giorni precedenti (alzandola) ma non pagheresti il valore del giorno dopo ma sempre la media. Non so se mi sono spiegato ;-)

**Comment by CreasolTech** [comment]
Ciao.
pun_sensor va benissimo per fare la stima dei consumi.
Il valore invece del pun orario sono utili per:
* conoscere la remunerazione dell'energia immessa in rete (fotovoltaico)
* per stabilire una strategia di gestione dell'energia al fine di consentire l'immissione di energia quando il PUN è massimo
* in inverno per limitare i consumi quando il PUN è massimo e aumentarli quando è minimo, solo nell'ottica di "aiutare la rete" (dal momento che poi le utilities fatturano in base al PUN medio mensile) e di stabilizzazione del PUN (se tutti consumassero meno quando il PUN è alto, il PUN si stabilizzerebbe e non ci sarebbero delle punte alte).
Da quando è iniziata la guerra in Ukraina mi sono posto l'obiettivo di ridurre i consumi al mattino e tardo pomeriggio per aiutare la rete, e vedo che è migliorato anche il ritorno economico dal GSE.
Non so però dove siano contenuti i dati del PUN del giorno successivo (che immagino siano disponibili dopo le 14 circa).

**Comment by virtualdj** [comment]
> Non so però dove siano contenuti i dati del PUN del giorno successivo (che immagino siano disponibili dopo le 14 circa).

Beh in realtà i dati sono sempre nello stesso file XML scaricabile da [QUI](https://www.mercatoelettrico.org/It/download/DownloadDati.aspx?val=MGP_Prezzi).

Supponiamo di inserire come data inizio quella odierna (23/12/2023) e come fine 25/12/2023; se lo scarichi prima delle 12:58 otterrai uno ZIP con dentro un unico file `20231223MGPPrezzi.xml` che a te non interessa. Se invece lo scarichi dopo quell'ora, con le stesse date, nel file ZIP ci saranno dentro due file, con il secondo che è `20231224MGPPrezzi.xml` (cioè relativo a domani) con i prezzi del PUN ora per ora (1-24).

**Comment by CreasolTech** [comment]
Già, è vero. Informazione utilissima questa.
Ti chiedo un'altra informazione: i dati giornalieri iniziando dall'ora 1: cosa significa?
Dalle 00:00 all' 1:00 oppure dall'1:00 alle 2:00 ?
Grazie

**Comment by virtualdj** [comment]
> i dati giornalieri iniziando dall'ora 1: cosa significa?
> Dalle 00:00 all' 1:00 oppure dall'1:00 alle 2:00 ?

Dovrebbe essere l'ora finale, quindi 1 nell'XML significa dalle 0:00 alle 1:00 e 24 dalle 23:00 alle 0:00.
