### ISSUE TITLE
Errore in "Esamina le righe non vuote a partire dalla seconda"

### ISSUE THREAD

**Issue by ossodue** [virtualdj/pun-fasce#3]
Ciao,
volevo informarti che il loop
`for row in range(2, sheet.max_row)`
deve essere modificato in
`for row in range(2, sheet.max_row+1)`
perché altrimenti non considera mai l'ultima riga del foglio excel e di conseguenza i dati dell'ultimo mese non sono proprio corretti. 

Buona giornata e grazie per lo script.

**Comment by virtualdj** [comment]
Ciao, grazie!!! Che scemo 🤦‍♂️ ecco perché nel mese più recente i prezzi uscivano sempre diversi (per poi "sistemarsi" successivamente)... E non ci ho nemmeno pensato a capire perché! 😞
